#!/bin/bash

sysctl net.ipv4.ip_forward=1

interface=$(nmcli d | grep wifi | cut -d ' ' -f1)

iptables -P INPUT DROP
iptables -P FORWARD DROP
iptables -P OUTPUT DROP


# iptables -A FORWARD -i xenbr0 -j ACCEPT

iptables -A PREROUTING -t nat -i wlp3s0 -p tcp --dport 80 -j DNAT --to-destination 10.0.0.3:80
iptables -A PREROUTING -t nat -i wlp3s0 -p tcp --dport 8000 -j DNAT --to-destination 10.0.0.5:80
iptables -A PREROUTING -t nat -i wlp3s0 -p tcp --dport 21 -j DNAT --to-destination 10.0.0.2:21

iptables -A FORWARD -p tcp -d 10.0.0.3 --dport 80 -j ACCEPT
iptables -A FORWARD -p tcp -d 10.0.0.5 --dport 80 -j ACCEPT
iptables -A FORWARD -p tcp -d 10.0.0.2 --dport 21 -j ACCEPT

iptables -t nat -A POSTROUTING -o wlp3s0 -j MASQUERADE

echo "Configuración funcionando!"


#iptables -t filter -A INPUT -i $interface -j ACCEPT
#iptables -t nat -A OUTPUT -o $interface -j ACCEPT
#iptables -t filter -A FORWARD -i $interface -j ACCEPT
#iptables -t filter -A FORWARD -i $interface -j ACCEPT

#iptables -t nat -A PREROUTING -i $interface -p tcp --dport 80 -j DNAT --to 10.0.0.3:80
#iptables -t nat -A PREROUTING -i $interface -p tcp --dport 8000 -j DNAT --to 10.0.0.5:80
#iptables -t nat -A PREROUTING -i $interface -p tcp --dport 21 -j DNAT --to 10.0.0.2:21

# echo iptables -t nat -A INPUT -i $interface -j ACCEPT
# echo iptables -t nat -A INPUT -o $interface -j ACCEPT
# iptables -t nat -A FORWARD -i $interface -j ACCEPT
# echo iptables -t nat -A FORWARD -o $interface -j ACCEPT
# echo iptables -t nat -A OUTPUT -i $interface -j ACCEPT
# echo iptables -t nat -A OUTPUT -o $interface -j ACCEPT

# echo iptables -t nat -A PREROUTING -i $interface -p tcp --dport 80 -j DNAT --to 10.0.0.2
